print("--------- CALCULATOR ---------- ")
x = int(input("num1 : "))
y = int(input("num2 : "))
print("=============================== ")
print(x,"+",y,"=",x+y)
print(x,"-",y,"=",x-y)
print(x,"x",y,"=",x*y)
print(x,"/",y,"=",x/y)
print("=============================== ")